#####################################################################################################################
#
#   ModBus-KNX Gateway script - sending data via simple configuration
#   The script and the configuration file are provided under Apache 2.0 license.
#   Author: MBizm [https://github.com/MBizm]
#
#   The ModBus-KNX Gatway sends data from a ModBus appliance to KNX. It is based on the IP/KNX Gateway device with an installed KNXD library.
#   All configuration can be done via the CONFIG.yaml file. Follow the below instruction. The configuration file contains the following sections:
#     -config section:
#           -- general configurations for executing the script
#           -- define your intended logging level here ("off", "error", "info") with "info" providing information about each sent attribute
#     - modbusAppliance:
#           -- defines all physical appliances that shall be linked. The script supports multiple ModBus devices as source for data sent to the KNX bus.
#           -- Attributes are linked via the [modbusApplID] attribute id that every attribute needs to define
#           -- knxdIP represents the IP/KNX bus devices IP
#     - attributes:
#           -- list of attributes transferred between the ModBus appliance and the KNX bus
#           -- script currently only supports ModBus-READ and KNX-WRITE instructions, defined by [type] value "modbus2knx" (TODO)
#           -- [modbusAddrDec] defines the ModBus address in decimal representation, [modbusFormat] the ModBus attribute data type - currently only "float" is supported (TODO)
#           -- [modbusAddrDec] allows the automatic calculation of the sum of several ModBus addresses by "[addr1, addr2]" representation
#           -- [knxAddr] defines the KNX address in "x/y/z" notation, [knxFormat] the KNX DPT data type - currently only "DPT14" is supported (TODO)
#           -- [updFreq] defines the frequency the attribute is updated:
#               --- "very high"   - updates once every 10sec, be careful not to flood the bus with too many requests
#               --- "high"        - updates once every minute
#               --- "medium"      - updates once every hour
#               --- "low"         - updates once every 24hours
#
#####################################################################################################################

configSet:  ModBus - KNXD configuration data
configNote: >
  Maintain your configuration for your devices to be linked here. ModBus data retrieved will be forwarded to corresponding KNX address. Multiple ModBus appliance can be configured.
  First section covers ModBus and KNX endpoint information, second section will list attributes that gateway shall update.
configVersion:  0.1
configVerbose:  "info"

#################################################
#       ModBus and KNX endpoint information     #
#################################################
# maintain modbus server information, can be multiple
modbusAppliance:
  - modbusApplID: 0
    modbusName:   "Solar Inverter"
    modbusIP:     "192.168.100.1"
    modbusPort:   "1502"
  - modbusApplID: 1
    modbusName:   "Heating system"
    modbusIP:     "192.168.100.7"
    modbusPort:   "1502"
# maintain IP of KNX IP/Bus gateway device
knxdAppliance:
  knxdIP:     "192.168.100.222"

#################################################
#   ModBus and KNXD attribute parametrization   #
#################################################
attributes:
  - name:           "Solar Current Power"
    type:           "modbus2knx"
    modbusApplID:   0
    modbusAddrDec:  100
    modbusFormat:   "float"
    knxAddr:        "5/5/5"
    knxFormat:      "DPT14"
    updFreq:        "very high"
  - name:           "Solar Daily Power"
    type:           "modbus2knx"
    modbusApplID:   0
    modbusAddrDec:  [101, 102, 103]
    modbusFormat:   "float"
    knxAddr:        "5/5/6"
    knxFormat:      "DPT14"
    updFreq:        "high"
  - name:           "Current Power Consumption"
    type:           "modbus2knx"
    modbusApplID:   1
    modbusAddrDec:  6
    modbusFormat:   "float"
    knxAddr:        "5/5/7"
    knxFormat:      "DPT14"
    updFreq:        "very high"