#####################################################################################################################
#
#   KNXBridge template configuration file
#   The script and the configuration file are provided under Apache 2.0 license.
#   Author: MBizm [https://github.com/MBizm]
#
#   See detailed explanation here: https://github.com/MBizm/KNXBridge/blob/main/README.md
#
#####################################################################################################################

configSet:  KNX Bridge for Modbus and ZigBee configuration
configNote: >
  The configuration file declaring the client and their respective attributes to be exchanged is located in *~/.knx/bridge/CONFIG.yaml*.
  Folder and initial configuration template will be created by installation script.
configVersion:  0.3
configVerbose:  "info"

#################################################
#            Gateway information                #
#################################################
# maintain IP of KNX IP/Bus gateway device
knxdAppliance:
  knxdIP:     <ENTER YOUR IP HERE>

# comment if ZigBee Gateway is not available
deconzAppliance:
    deConzIP:     <ENTER YOUR IP HERE>
    deConzPort:   <ENTER YOUR PORT HERE>
    deConzToken:  <ENTER YOUR TOKEN HERE>

#################################################
#   external appliance endpoint information     #
#################################################
# maintain modbus server information, can be multiple
modbusAppliance:
  - modbusApplID: 0
    modbusName:   "Solar Inverter"
    modbusIP:     <ENTER YOUR IP HERE>
    modbusPort:   "1502"
#  - modbusApplID: 1
#    modbusName:   "Heating system"
#    modbusIP:     <ENTER YOUR IP HERE>
#    modbusPort:   "1502"

# maintain MQTT Broker information
mqttAppliance:
  - mqttApplID:   100
    mqttName:     "Central MQTT Broker Instance"
    mqttIP:       <ENTER YOUR IP HERE>
#    mqttPort:      "1883"
#    mqttUser:      "myUser"
#    mqttPasswd:    "myPasswd"

# maintain ZigBee client information
# some client may have multiple entries if mapped to multiple types (e.g. smoke sensor - light and sensor)
zigbeeAppliance:
  - zigbeeApplID: 0
    zigbeeName:   "Light Living Room"
    deConzID:     2
    deConzType:   "lights"
  #   Garage Gate Sensor   #
  - zigbeeApplID: 1a
    zigbeeName:   "Sensor Garage Gate - Closing State"
    deConzID:     2
    deConzType:   "sensors"
  - zigbeeApplID: 1b
    zigbeeName:   "Sensor Garage Gate - Temperature"
    deConzID:     3
    deConzType:   "sensors"
  - zigbeeApplID: 1c
    zigbeeName:   "Sensor Garage Gate - Temperature"
    deConzID:     4
    deConzType:   "sensors"
  #####################
  #   Smoke sensors   #
  #####################
  #   Technical equipment room   #
  - zigbeeApplID: 2a
    zigbeeName:   "Sensor TER - Smoke"
    deConzID:     7
    deConzType:   "sensors"
  - zigbeeApplID: 2b
    zigbeeName:   "Sensor TER - Temperature"
    deConzID:     8
    deConzType:   "sensors"

#################################################
#   ModBus and KNXD attribute parametrization   #
#################################################
attributes:
  #   Solar Inverter   #
  - name:           "Current AC Power"
    type:           "modbus2knx"
    modbusApplID:   0
    modbusAddrDec:  100
    modbusFormat:   "float"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "14.056"
    updFreq:        "very high"
  - name:           "Daily Yield Power"
    type:           "modbus2knx"
    modbusApplID:   0
    modbusAddrDec:  101
    modbusFormat:   "float"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "13.001"
    updFreq:        "medium"
  - name:           "Daily Yield Power - Contract"
    type:           "modbus2knx"
    modbusApplID:   0
    modbusAddrDec:  322
    modbusFormat:   "float"
    function:       "val(0)"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "5.006"
    updFreq:        "medium"
  - name:           "Current Power Consumption"
    type:           "modbus2knx"
    modbusApplID:   0
    modbusAddrDec:  [106, 108, 116]
    modbusFormat:   "float"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "14.056"
    updFreq:        "very high"

  ####################
  #   MQTT clients   #
  ####################
  - name:           " Waterflow sensor"
    type:           "mqtt2knx"
    mqttApplID:     100
    mqttTopic:      "/waterflow"
#    function:       "lt(10)"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "14.077"   # liter/sec

  #   Garage Gate Sensore   #
  - name:           "Garage Gate Closing State"
    type:           "zigbee2knx"
    zigbeeApplID:   1a
    zigbeeAttr:     "open"
    zigbeeFormat:   "boolean"
    function:       "inv"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "1.002"
    updFreq:        "very high"
  - name:           "Garage Gate Vibration"
    type:           "zigbee2knx"
    zigbeeApplID:   1c
    zigbeeAttr:     "vibration"
    zigbeeFormat:   "boolean"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "1.002"
    updFreq:        "very high"
  - name:           "Garage Gate Temperature"
    type:           "zigbee2knx"
    zigbeeApplID:   1b
    zigbeeAttr:     "temperature"
    zigbeeFormat:   "int"
    function:       "div(100)"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "9.001"
    updFreq:        "low"
  - name:           "Garage Gate NoConnection"
    type:           "zigbee2knx"
    zigbeeApplID:   1a
    zigbeeAttr:     "lastupdated"
    zigbeeFormat:   "date"
    function:       "timedeltaGT(1800)"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "1.002"
    updFreq:        "medium"
  - name:           "Garage Gate LowBattery"
    type:           "zigbee2knx"
    zigbeeApplID:   1b
    zigbeeAttr:     "battery"
    zigbeeFormat:   "int"
    zigbeeSection:  "config"
    function:       "lt(10)"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "1.002"
    updFreq:        "low"


  #####################
  #   Smoke sensors   #
  #####################
  #   TER   #
  - name:           "TER Fire"
    type:           "zigbee2knx"
    zigbeeApplID:   2a
    zigbeeAttr:     "fire"
    zigbeeFormat:   "boolean"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "1.002"
    updFreq:        "very high"
  - name:           "TER Test"
    type:           "zigbee2knx"
    zigbeeApplID:   2a
    zigbeeAttr:     "test"
    zigbeeFormat:   "boolean"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "1.002"
    updFreq:        "very high"
  - name:           "TER LowBattery"
    type:           "zigbee2knx"
    zigbeeApplID:   2a
    zigbeeAttr:     "lowbattery"
    zigbeeFormat:   "boolean"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "1.002"
    updFreq:        "medium"
  - name:           "TER NoConnection"
    type:           "zigbee2knx"
    zigbeeApplID:   2a
    zigbeeAttr:     "lastupdated"
    zigbeeFormat:   "date"
    function:       "timedeltaGT(900)"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "1.002"
    updFreq:        "medium"
  - name:           "TER TemperatureAlarm"
    type:           "zigbee2knx"
    zigbeeApplID:   2b
    zigbeeAttr:     "temperature"
    zigbeeFormat:   "int"
    function:       "div(100), gt(40)"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "1.002"
    updFreq:        "medium"
  - name:           "TER Temperature"
    type:           "zigbee2knx"
    zigbeeApplID:   2b
    zigbeeAttr:     "temperature"
    zigbeeFormat:   "int"
    function:       "div(100)"
    knxAddr:        <ENTER YOUR KNX ADDRESS HERE>
    knxFormat:      "9.001"
    updFreq:        "medium"